#!/usr/bin/env python3
"""Generated by agents-team. Run a read-only adapter health check."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    validator = Path(__file__).with_name("validate_team_collaboration.py")
    result = subprocess.run([sys.executable, str(validator), str(root)], text=True)
    if result.returncode == 0:
        print("doctor: healthy")
    else:
        print("doctor: blocked")
    return result.returncode


if __name__ == "__main__":
    raise SystemExit(main())
