#!/usr/bin/env python3
"""Generated by agents-team. Validate a PR, its Goal Issue, and current-head evidence."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from pathlib import Path


PR_SECTIONS = [
    "关联任务", "风险等级", "实际改动", "范围偏差", "必须完成项证据",
    "测试门禁", "行为验收", "QA 独立性与结论", "剩余风险", "回滚方式", "失败记录",
]
ISSUE_SECTIONS = ["Goal", "必须完成", "验收门禁", "任务边界", "风险等级", "依赖与阻塞条件", "失败处理与回滚"]
HEADING = re.compile(r"^#{2,6}\s+(.+?)\s*$", re.MULTILINE)
ISSUE_LINK = re.compile(r"\b(?:close[sd]?|fix(?:e[sd])?|resolve[sd]?)\s+#(\d+)\b", re.IGNORECASE)
PLACEHOLDER = re.compile(r"<[^>]+>|待验收|待补充|TODO", re.IGNORECASE)


def sections(body: str) -> dict[str, str]:
    matches = list(HEADING.finditer(body or ""))
    result: dict[str, str] = {}
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(body)
        result[match.group(1).strip()] = body[match.end():end].strip()
    return result


def scalar(block: str, name: str) -> str:
    match = re.search(rf"(?mi)^\s*{re.escape(name)}\s*:\s*(.+?)\s*$", block)
    return match.group(1).strip() if match else ""


def valid_timestamp(value: str) -> bool:
    try:
        datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return False
    return bool(value)


def validate(pr_body: str, issue_body: str, head_sha: str) -> list[str]:
    errors: list[str] = []
    pr = sections(pr_body)
    issue = sections(issue_body)
    for name in PR_SECTIONS:
        if not pr.get(name, "").strip():
            errors.append(f"PR missing section: {name}")
    for name in ISSUE_SECTIONS:
        if not issue.get(name, "").strip():
            errors.append(f"Issue missing section: {name}")
    if not ISSUE_LINK.search(pr_body or ""):
        errors.append("PR must close a numbered Issue")
    if PLACEHOLDER.search(pr_body or ""):
        errors.append("PR contains unresolved placeholders")

    tests = pr.get("测试门禁", "")
    for name in ("gate", "command", "exitCode", "passed", "failed", "skipped", "timestamp", "commitSha", "artifact"):
        if not scalar(tests, name):
            errors.append(f"test evidence missing: {name}")
    if scalar(tests, "exitCode") != "0" or scalar(tests, "failed") != "0":
        errors.append("test evidence is not successful")
    commit_sha = scalar(tests, "commitSha")
    if commit_sha and commit_sha != head_sha:
        errors.append(f"test evidence commitSha {commit_sha} does not match head.sha {head_sha}")
    timestamp = scalar(tests, "timestamp")
    if timestamp and not valid_timestamp(timestamp):
        errors.append("test evidence timestamp is not ISO 8601")
    artifact = scalar(tests, "artifact")
    if artifact and not re.match(r"https://", artifact):
        errors.append("test evidence artifact must be an HTTPS URL")

    risk = pr.get("风险等级", "") + "\n" + issue.get("风险等级", "")
    if re.search(r"\bL[23]\b", risk, re.IGNORECASE):
        qa = pr.get("QA 独立性与结论", "")
        if not re.search(r"独立上下文\s*[：:]\s*是", qa):
            errors.append("L2/L3 QA must use an independent context")
        if not re.search(r"结论\s*[：:]\s*PASS\b", qa, re.IGNORECASE):
            errors.append("L2/L3 QA verdict must be PASS")
    return errors


def fetch_issue(repo: str, number: int, token: str) -> str:
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/issues/{number}",
        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {token}", "User-Agent": "agents-team-gate"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return str(json.loads(response.read().decode("utf-8")).get("body") or "")
    except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot read linked Issue: {exc}") from exc


def fetch_pull_request(repo: str, branch: str, token: str) -> dict[str, object]:
    owner = repo.split("/", 1)[0]
    query = urllib.parse.urlencode({"state": "open", "head": f"{owner}:{branch}"})
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/pulls?{query}",
        headers={"Accept": "application/vnd.github+json", "Authorization": f"Bearer {token}", "User-Agent": "agents-team-gate"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            pulls = json.loads(response.read().decode("utf-8"))
    except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"cannot find pull request for pushed branch: {exc}") from exc
    if not isinstance(pulls, list) or len(pulls) != 1 or not isinstance(pulls[0], dict):
        raise RuntimeError(f"expected exactly one open pull request for branch {branch}")
    return pulls[0]


def pull_request_from_event(event: dict[str, object], token: str) -> dict[str, object]:
    pull_request = event.get("pull_request")
    if isinstance(pull_request, dict) and pull_request:
        return pull_request
    ref = str(event.get("ref") or "")
    repo_data = event.get("repository")
    repo = str(repo_data.get("full_name") or "") if isinstance(repo_data, dict) else ""
    if not ref.startswith("refs/heads/") or not event.get("after") or not repo:
        raise RuntimeError("event is neither a pull_request nor a branch push")
    if not token:
        raise RuntimeError("GITHUB_TOKEN is required to resolve a pushed branch to its open PR")
    return fetch_pull_request(repo, ref.removeprefix("refs/heads/"), token)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--event", type=Path, required=True)
    parser.add_argument("--issue-body-file", type=Path)
    args = parser.parse_args()
    event = json.loads(args.event.read_text(encoding="utf-8"))
    token = os.environ.get("GITHUB_TOKEN", "")
    try:
        pull_request = pull_request_from_event(event, token)
    except RuntimeError as exc:
        print(f"Agents-Team gate blocked: {exc}")
        return 1
    if pull_request.get("draft"):
        print("draft PR: strict contract deferred until ready for review")
        return 0

    pr_body = str(pull_request.get("body") or "")
    head_sha = str((pull_request.get("head") or {}).get("sha") or "")  # head.sha
    repo = str((event.get("repository") or {}).get("full_name") or os.environ.get("GITHUB_REPOSITORY") or "")
    linked = ISSUE_LINK.search(pr_body)
    if not head_sha or not repo or linked is None:
        errors = ["event is missing repository, head.sha, or linked Issue"]
    else:
        if args.issue_body_file:
            issue_body = args.issue_body_file.read_text(encoding="utf-8")
        else:
            if not token:
                print("Agents-Team gate blocked: GITHUB_TOKEN is required")
                return 1
            try:
                issue_body = fetch_issue(repo, int(linked.group(1)), token)
            except RuntimeError as exc:
                print(f"Agents-Team gate blocked: {exc}")
                return 1
        errors = validate(pr_body, issue_body, head_sha)

    if errors:
        print("Agents-Team PR contract failed:")
        for error in errors:
            print(f"- {error}")
        return 1
    print("Agents-Team PR contract passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
