#!/usr/bin/env python3
"""Generated by agents-team. Self-contained project validator."""

import json
import hashlib
import re
import sys
from pathlib import Path


REQUIRED = [
    "AGENTS.md",
    ".codex/team-collaboration.json",
    ".codex/scripts/validate_pr_contract.py",
    ".codex/scripts/doctor_team_collaboration.py",
    ".github/ISSUE_TEMPLATE/team-goal.yml",
    ".github/ISSUE_TEMPLATE/critical-goal.yml",
    ".github/pull_request_template.md",
]
BLOCK_RE = re.compile(
    r"<!-- TEAM-COLLABORATION:START(?: [^>]*)? -->\n.*?\n<!-- TEAM-COLLABORATION:END -->\n?",
    re.DOTALL,
)


def sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def main() -> int:
    root = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    errors = [f"missing: {path}" for path in REQUIRED if not (root / path).is_file()]
    config_path = root / ".codex/team-collaboration.json"
    if config_path.is_file():
        try:
            config = json.loads(config_path.read_text(encoding="utf-8"))
            if config.get("mechanism", {}).get("id") != "agents-team":
                errors.append("invalid mechanism.id")
            for target, expected in config.get("managedFiles", {}).items():
                if target == "AGENTS.md#TEAM-COLLABORATION":
                    agents_path = root / "AGENTS.md"
                    matches = BLOCK_RE.findall(agents_path.read_text(encoding="utf-8")) if agents_path.is_file() else []
                    if len(matches) != 1:
                        errors.append("missing or malformed AGENTS managed block")
                        continue
                    data = matches[0].encode("utf-8")
                else:
                    managed_path = root / target
                    if not managed_path.is_file():
                        errors.append(f"missing: {target}")
                        continue
                    data = managed_path.read_bytes()
                if sha256(data) != expected:
                    errors.append(f"managed file drift: {target}")
        except (OSError, json.JSONDecodeError) as exc:
            errors.append(f"invalid config: {exc}")
    agents = root / "AGENTS.md"
    if agents.is_file() and "TEAM-COLLABORATION:START" not in agents.read_text(encoding="utf-8"):
        errors.append("missing AGENTS managed block")
    for error in errors:
        print(error)
    if not errors:
        print("team collaboration project adapter: valid")
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
